# Generated by Django 3.0.5 on 2020-04-21 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuystomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/customers/pictures/', verbose_name='profile picture')),
                ('delivery_address', models.TextField(blank=True, max_length=200)),
                ('orders_made', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rider',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/riders/pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/stores/pictures/', verbose_name='profile picture'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
