# Generated by Django 3.0.5 on 2020-04-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200421_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuystomer',
            new_name='Customer',
        ),
    ]
