# Generated by Django 3.0.5 on 2020-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveried',
            field=models.BooleanField(default=False, verbose_name='deliveried to customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up',
            field=models.BooleanField(default=False, verbose_name='picked up by the rider'),
        ),
    ]
